version: '3'

services:
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123
      - MSSQL_PID=Developer
    volumes:
    - ./mssqldata:/var/opt/mssql

  q2:
    build:
      context: ./q2
    image: q2
    environment:
      - UID=SA
      - PWD=Password123

    volumes:
      - ./q2:/code

  q3:
    build:
      context: ./q3
    image: q3
    environment:
      - UID=SA
      - PWD=Password123

    volumes:
      - ./q3:/code