version: '3'

services:

  q2:
    build:
      context: ./q2
    image: q2
    environment:
      - UID=SA
      - PWD=Password123

    volumes:
      - ./q2:/code

  q3:
    build:
      context: ./q3
    image: q3
    environment:
      - UID=SA
      - PWD=Password123

    volumes:
      - ./q3:/code